### ISSUE TITLE
Enhancement (Video support)

### ISSUE THREAD

**Issue by solcre-gr** [kolkov/ngx-gallery#1]
There is any plans to add videos in the gallery?

**Comment by kolkov** [comment]
Hi! Thanks for your request.
Do you want to use video from youtube or from other resources?

**Comment by solcre-gr** [comment]
Hi!, thank u for your response, i need to use it with local videos, like .mp4 or .avi.

**Comment by hverma** [comment]
+1

**Comment by hverma** [comment]
@kolkov wondering if you have a targate date on this enhancement. Thx in advance!

**Comment by kolkov** [comment]
Thanks for your interesting. I finishing a big project at next week, after that I want to do this enchancement.
If you have a PR, it's speed up my work.

**Comment by Simbaclaws** [comment]
@kolkov 

You forked the project from lukasz-galka's project right?
In which case you saw the pull request that Muhammad Altabba made.

If you could kindly add his code to your repository that would be great...

His code can be found here:
https://github.com/lukasz-galka/ngx-gallery/pull/257/files/b5d80e13a9e376d1065497a464b126f72066e2c1#diff-90871a8f9a0306e34e7bee9f707e475e

In his pull request for lukasz-galka's project.

Please make this work, I can't seem to find any angular gallery package that supports video currently.

**Comment by kolkov** [comment]
Hi! It's not a fork, but 100% compatible by API. I will try to implement that PR into this project.
Thanks.

**Comment by Simbaclaws** [comment]
I added video support to my pull request here:
https://github.com/kolkov/ngx-gallery/pull/23

**Comment by Simbaclaws** [comment]
Pull Request has been merged, I suppose this issue can be set to solved. I don't have the ability to do so though.

**Comment by kolkov** [comment]
@Simbaclaws thanks for the PR. Try latest version please.
