### ISSUE TITLE
Doesn't work with Angular 9?

### ISSUE THREAD

**Issue by zmojsovski** [kolkov/ngx-gallery#10]
Hello, I've tried using this with Angular 9 and it won't show the gallery images ( it doesn't give errors aswell)

imported it in the app.module:

`import { NgxGalleryModule } from '@kolkov/ngx-gallery';` 
Also added it into imports here is the component and how I use it:
```
import { AlertifyService } from './../../../_services/alertify.service';
import { UserService } from './../../../_services/user.service';
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/_models/user';
import { ActivatedRoute } from '@angular/router';
import { NgxGalleryOptions, NgxGalleryImage, NgxGalleryAnimation } from '@kolkov/ngx-gallery';


@Component({
  selector: 'app-member-detail',
  templateUrl: './member-detail.component.html',
  styleUrls: ['./member-detail.component.css']
})
export class MemberDetailComponent implements OnInit {
  user: User;
  galleryOptions: NgxGalleryOptions[];
  galleryImages: NgxGalleryImage[];

  constructor(private userService: UserService, private alertify: AlertifyService, private route: ActivatedRoute) { }

  ngOnInit() {
    this.route.data.subscribe(data => {
      this.user = data['user'];
    });
    this.galleryOptions = [
      {
        width: '500px',
        height: '500px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide,
      },
      {
        imagePercent: 100
      },
      {
        preview: false
      }
    ];
    this.galleryImages = this.getImages();
  }

  getImages() {
    const imageUrls = [];
    for (const photo of this.user.photos) {
      imageUrls.push({
        small: photo.url,
        medium: photo.url,
        big: photo.url,
        description: photo.description
      });
    }
    return imageUrls;
  }
```
I also debugged and checked for galleryImages variable it gets the values but the images are not shown in the browser.

`<ngx-gallery [options]="galleryOptions" [images]="galleryImages" class="ngx-gallery"></ngx-gallery>`

**Comment by kolkov** [comment]
Hi! Maybe this will help?
https://github.com/kolkov/ngx-gallery/issues/8

**Comment by zmojsovski** [comment]
Yes, that solved my problem, Thank you!

**Comment by ajyadav223** [comment]
I have added the .ngx-gallery class as suggested,
But stillfacing the same issue

**Comment by ajyadav223** [comment]
> Yes, that solved my problem, Thank you!

Hi zmojsovski 
I have added the .ngx-gallery class as suggested,
But stillfacing the same issue like you.
could you please let me know what quick fix you have done.
Thanks,
Ajyadav223

**Comment by BrunoElo** [comment]
> > Yes, that solved my problem, Thank you!
> 
> Hi zmojsovski
> I have added the .ngx-gallery class as suggested,
> But stillfacing the same issue like you.
> could you please let me know what quick fix you have done.
> Thanks,
> Ajyadav223

Try with `display: block;`

**Comment by BrunoElo** [comment]
> Hello, I've tried using this with Angular 9 and it won't show the gallery images ( it doesn't give errors aswell)
> 
> imported it in the app.module:
> 
> `import { NgxGalleryModule } from '@kolkov/ngx-gallery';`
> Also added it into imports here is the component and how I use it:
> 
> ```
> import { AlertifyService } from './../../../_services/alertify.service';
> import { UserService } from './../../../_services/user.service';
> import { Component, OnInit } from '@angular/core';
> import { User } from 'src/app/_models/user';
> import { ActivatedRoute } from '@angular/router';
> import { NgxGalleryOptions, NgxGalleryImage, NgxGalleryAnimation } from '@kolkov/ngx-gallery';
> 
> 
> @Component({
>   selector: 'app-member-detail',
>   templateUrl: './member-detail.component.html',
>   styleUrls: ['./member-detail.component.css']
> })
> export class MemberDetailComponent implements OnInit {
>   user: User;
>   galleryOptions: NgxGalleryOptions[];
>   galleryImages: NgxGalleryImage[];
> 
>   constructor(private userService: UserService, private alertify: AlertifyService, private route: ActivatedRoute) { }
> 
>   ngOnInit() {
>     this.route.data.subscribe(data => {
>       this.user = data['user'];
>     });
>     this.galleryOptions = [
>       {
>         width: '500px',
>         height: '500px',
>         thumbnailsColumns: 4,
>         imageAnimation: NgxGalleryAnimation.Slide,
>       },
>       {
>         imagePercent: 100
>       },
>       {
>         preview: false
>       }
>     ];
>     this.galleryImages = this.getImages();
>   }
> 
>   getImages() {
>     const imageUrls = [];
>     for (const photo of this.user.photos) {
>       imageUrls.push({
>         small: photo.url,
>         medium: photo.url,
>         big: photo.url,
>         description: photo.description
>       });
>     }
>     return imageUrls;
>   }
> ```
> 
> I also debugged and checked for galleryImages variable it gets the values but the images are not shown in the browser.
> 
> `<ngx-gallery [options]="galleryOptions" [images]="galleryImages" class="ngx-gallery"></ngx-gallery>`

Lol...I'm here to due to the same tutorial..🌚
