### ISSUE TITLE
I don't quite understand what's going on with the GalleryOptions.

### ISSUE THREAD

**Issue by aardvark79** [kolkov/ngx-gallery#12]
Why is it expecting an array? Why is it not just an object with key/value pairs?

**Comment by kolkov** [comment]
I saved this for compatibility with the original abandoned library.  There is an array for different screen resolutions.

**Comment by windcloak** [comment]
You have three resolutions, big, medium and small as opposed to just one resolution. So you are not linking a key to 1 value, but a key to 3 values, hence why it's more like an array of maps instead of key/value.
