### ISSUE TITLE
base64 working example

### ISSUE THREAD

**Issue by gmareater** [kolkov/ngx-gallery#17]
hi
thanx for you work, currently i'm trying to show images with base64, but i doesn't work (and i almost tried all suggestion from lukasz-galka repo

so, could you provide a working example so i could get what's wrong here?

i used : this.sanitizer.bypassSecurityTrustUrl and  bypassSecurityTrustResourceUrl , none of them worked

**Comment by cyrilinho** [comment]
Hi, 
I don't know if it will help you, but this is what I did :

base64 : string 
`var imageUrl : string = 'data:image/jpeg;base64,' + base64;`
`var img : NgxGalleryImage;`
`img = {`   
`   small : imageUrl,`
`   medium: imageUrl,`
`   big: imageUrl `
`}`
`this.galleryImages.push(img);`

**Comment by kolkov** [comment]
Now we can put URL by `URL.createObjectURL(blob) `as addition feature
