### ISSUE TITLE
latest version is not supporting with .webp format of images. @kolkov/ngx-gallery angular 8

### ISSUE THREAD

**Issue by saifansari2** [kolkov/ngx-gallery#25]
latest version is not supporting with .webp format of images..

its working with only jpeg jpg format 

plz help me asap

i am waiting for any help

**Comment by juanmalm** [comment]
having same issue

**Comment by kolkov** [comment]
Will be fixed in next 1.2.x version.

**Comment by kolkov** [comment]
@juanmalm try latest 1.2.1 version please

**Comment by juanmalm** [comment]
Sorry @kolkov, still not working in my case :(
I'll send you a private message with the webp image file URL I'm using.
