### ISSUE TITLE
if url doesn't have img extension type is marked unknown and the img doesnt work

### ISSUE THREAD

**Issue by feedyourmind** [kolkov/ngx-gallery#28]
Hi, great work, very cool project. 
the images don't display (the src is set to '#'). 
i am using firebase storage to host the images. the downloadurl generated does not have a 'jpg' extension. 
I looked into the sourcecode and i saw that even if you specify type in the NgxGalleryImage (when passing in the gallery images), it gets overriden later on by NgxGalleryService .getFileType (fileSource: string): string { ...  
https://github.com/kolkov/ngx-gallery/blob/9e91e810e65edfcefdf62130bd79681d4e8ac9cb/projects/gallery/src/lib/ngx-gallery.service.ts :  line 60
If the type is explicitly specified, it should be respected, otherwise image ulrs that dont' have a predefined extension don't work (like in my case with firebase storage buckets) .

**Comment by jwwitherspoon** [comment]
Is there a workaround for this issue? I am having the same trouble with this library and would love to use it sooner rather than later.

**Comment by psd24** [comment]
I am also having the same problem. I wish I could use it too. I am waiting. Thanks!

**Comment by kolkov** [comment]
> I am also having the same problem. I wish I could use it too. I am waiting. Thanks!

I will see what can be fixed.  Because since it was originally a abandoned project for old versions of Angular, I did not go into all the details of the work of this library.

**Comment by Pritha-Roy** [comment]
This is an excellent plugin for Angular 9 image gallery. But I'm stuck as all my images come from s3 and the link doesn't end with file extension. Any workaround will be really helpful. I am also waiting. Thanks.

**Comment by Pritha-Roy** [comment]
> > I am also having the same problem. I wish I could use it too. I am waiting. Thanks!
> 
> I will see what can be fixed. Because since it was originally a abandoned project for old versions of Angular, I did not go into all the details of the work of this library.

I'm still waiting. Is there any fix yet?

**Comment by kolkov** [comment]
I think this week it should be fixed. Now I have a large project being put into operation, as soon as it is launched, I will immediately begin to solve the accumulated problems. You can speed up if you prepare PR in the 1.x branch.
Thanks.

**Comment by Pritha-Roy** [comment]
Hi! Any update on this?

**Comment by kolkov** [comment]
Try latest 1.2.3 version please.

**Comment by Pritha-Roy** [comment]
Thanks so much! It's working now.

**Comment by kolkov** [comment]
Thanks!
