### ISSUE TITLE
ERROR TypeError: "url is undefined

### ISSUE THREAD

**Issue by yuniers** [kolkov/ngx-gallery#3]
When I try reproduce the example of .README file I get this error:

```js
ERROR TypeError: "url is undefined"
    validateUrl kolkov-ngx-gallery.js:29
    getBackgroundUrl kolkov-ngx-gallery.js:38
    getSafeUrl kolkov-ngx-gallery.js:684
    View_NgxGalleryImageComponent_1 NgxGalleryImageComponent.html:7
    Angular 56
    RxJS 5
    Angular 9
NgxGalleryImageComponent.html:2:2
    View_NgxGalleryImageComponent_1 NgxGalleryImageComponent.html:2
    Angular 15
    RxJS 5
    Angular 9
```

My problem is related with `validateUrl` function used on:
https://github.com/kolkov/ngx-gallery/blob/d6f4bf473a224ae2916e7ecc35ac6bf69c41ef95/projects/gallery/src/lib/ngx-gallery.service.ts#L29

**Comment by kolkov** [comment]
Hi! What version of this package and Angular you are using?

**Comment by yuniers** [comment]
@kolkov I'm using Angular 8.2.14 and "@kolkov/ngx-gallery": "^1.0.9"

My image array is:

```js
[
  {
    "big": "http://localhost/wp-content/uploads/2019/05/la-guarida8.jpg",
    "description": "la-guarida8",
    "url": "http://localhost/wp-content/uploads/2019/05/la-guarida8.jpg"
  },
  {
    "big": "http://localhost/wp-content/uploads/2019/05/la-guarida3.jpg",
    "description": "la-guarida3",
    "url": "http://localhost/wp-content/uploads/2019/05/la-guarida3.jpg"
  },
  {
    "big": "http://localhost/wp-content/uploads/2019/05/la-guarida1.jpg",
    "description": "la-guarida1",
    "url": "http://localhost/wp-content/uploads/2019/05/la-guarida1.jpg"
  },
  {
    "big": "http://localhost/wp-content/uploads/2019/07/CARTEL-Gibara.jpg",
    "description": "cartel-gibara",
    "url": "http://localhost/wp-content/uploads/2019/07/CARTEL-Gibara.jpg"
  }
]
```

**Comment by kolkov** [comment]
Try to use this example at first:
https://github.com/kolkov/ngx-gallery/blob/master/projects/gallery-app/src/app/app.component.ts

**Comment by yuniers** [comment]
> Try to use this example at first:
> https://github.com/kolkov/ngx-gallery/blob/master/projects/gallery-app/src/app/app.component.ts

@kolkov
I follow that example but result is not like I was expect.

But, I can't use images without host because I use a CDN service to host my images.

**Comment by kolkov** [comment]
I mean that you should use small, big instead url.

**Comment by kolkov** [comment]
https://stackblitz.com/edit/kolkov-ngx-gallery like this.

**Comment by kolkov** [comment]
I can't reproduce this bug, provide an repo please.

**Comment by kolkov** [comment]
And notice please, `url` is link from thumbnails...

**Comment by zee85** [comment]
I think I ran into this same bug. The fullscreen preview image was undefined. I traced through the code and found that the older lib uses "large" instead of "big" for that image. This new API uses big instead of large.

**Comment by drb00** [comment]
I've got the same bug. It takes place when I try to use openPreview(idx) of NgxGalleryComponent.

`import {
  NgxGalleryOptions,
  NgxGalleryImage,
  NgxGalleryComponent
} from '@kolkov/ngx-gallery';

...
@ViewChild('gallary', { static: true }) gallary: NgxGalleryComponent;
...
this.gallary.openPreview(0);
`
