### ISSUE TITLE
Please add fileType property to NgxGalleryImage

### ISSUE THREAD

**Issue by axos88** [kolkov/ngx-gallery#33]
We store images by their md5 hashes, and do not include an extension. 
the NgxGalleryService determines file type based on extension only, and does not show images this way.
In case the file type cannot be determined, a white box is shown, as both *ngIfs evaluate to false.

It would be great if the file types could be overridden manually in the image object, or the system would default to using an image if the file type cannot be determined

**Comment by axos88** [comment]
#31

**Comment by kolkov** [comment]
Ttry latest version please.
