### ISSUE TITLE
I need to pass a token authorization (bearer).

### ISSUE THREAD

**Issue by andrejm7** [kolkov/ngx-gallery#35]
Good Morning

this library is too much.

but I have found problems with the links

this.galleryImages.push (
{
small: https://xxxx,
medium: https://xxxx,
big: https://xxxx
}
);

this is because I need to pass a token authorization (bearer).

how can i solve this problem of mine?

appreciate

**Comment by andrejm7** [comment]
????

**Comment by kolkov** [comment]
Hi! I think you need to use request interceptors, but I am not sure is it possible in this case.

**Comment by kolkov** [comment]
https://stackoverflow.com/questions/41013632/how-to-set-authorization-header-on-background-image-url

**Comment by kolkov** [comment]
https://stackoverflow.com/questions/47811784/passing-authorization-header-for-images-src-to-remote-server-in-ionic-page

**Comment by kolkov** [comment]
https://medium.com/javascript-in-plain-english/loading-images-with-authorization-8aab33663ba6

**Comment by kolkov** [comment]
https://stackoverflow.com/questions/38810956/set-background-image-to-a-blob-uri

**Comment by andrejm7** [comment]
thanks for the feedback. @kolkov 
i tried to do it according to this link .. look at the problem i have now .. i have 200 status but images .. but in ngx-gallery it doesn't show the image

https://github.com/lukasz-galka/ngx-gallery/issues/322#issuecomment-640988978

**Comment by kolkov** [comment]
> thanks for the feedback. @kolkov
> i tried to do it according to this link .. look at the problem i have now .. i have 200 status but images .. but in ngx-gallery it doesn't show the image
> 
> [lukasz-galka/ngx-gallery#322 (comment)](https://github.com/lukasz-galka/ngx-gallery/issues/322#issuecomment-640988978)

You need yo use blob url as image url.

**Comment by andrejm7** [comment]
yes .. i tried to do that .. but the image does not appear .. look at the problem ..

![image](https://user-images.githubusercontent.com/13546247/84440036-b2a70a80-ac0f-11ea-9f4a-16fa28ffba30.png)

**Comment by kolkov** [comment]
@andrejm7 Provide an repo please.

**Comment by andrejm7** [comment]
https://stackblitz.com/edit/angular-ivy-amefyb?file=src%2Fapp%2Fapp.component.ts

there is the problem.
Why doesn't 4 image appear?

I have a blob service return. And adding to galleryImages I can't see the image.

**Comment by kolkov** [comment]
https://github.com/kolkov/ngx-gallery/tree/test_blob try this solution or the same other.

**Comment by andrejm7** [comment]
i had this problem now ..

Error: Cannot read property 'startsWith' of undefined
Unable to display error. Open your browser's console to view.

I'm using like this

const objUrl = 'data: image/**jpeg**; base64,' + baseImage.image;

or

const objUrl = 'data: image/**png**; base64,' + baseImage.image;

**Comment by kolkov** [comment]
My example works, try to do by analogy...

**Comment by kolkov** [comment]
Try to post your support question with example to https://stackoverflow.com/ please.
Thanks!
