### ISSUE TITLE
Unable to get custom icons to work

### ISSUE THREAD

**Issue by sqljim** [kolkov/ngx-gallery#6]
I want to use custom icons, ideally Google's Material icons which are available [here](https://material.io/resources/icons/). But I'm falling at the first hurdle, I've added the required element into the options array, but the icons aren't updating.

I'm using the original stackblitz [here](https://stackblitz.com/edit/kolkov-ngx-gallery?file=src%2Fapp%2Fapp.component.ts), and altering the options from this:

```
      {
        width: '600px',
        height: '400px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide
      },
```

to this:

```
      {
        width: '600px',
        height: '400px',
        thumbnailsColumns: 4,
        arrowPrevIcon: "fa fa-arrow-circle-o-left",
        imageAnimation: NgxGalleryAnimation.Slide
      },
```

But nothing is happening. Can anyone point me in the right direction?

**Comment by kolkov** [comment]
Hi! Thanks for the reporting! I will try to reproduce.

**Comment by srhtkaya** [comment]
I have the same problem with custom icons under ngx-gallery-arrows component. Other custom icons under ngx-gallery-actions seems to work fine.
