### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by FFKL** [kolkov/ngx-gallery#62]
@kolkov Hi! Can I submit some pull requests? Is this project alive? I like this gallery. It's sad if it died :disappointed:

**Comment by kolkov** [comment]
Hi! Yes of course, it's alive.
Thanks!

**Comment by FFKL** [comment]
@kolkov cool!

**Comment by kolkov** [comment]
One big problem with slider animation. We need to change our template of gallery.
