### ISSUE TITLE
Mention about original lib

### ISSUE THREAD

**Issue by jrybinski** [kolkov/ngx-gallery#7]
Hey @kolkov.
First of all.
Great job with this one! 🤝 🍻 

I didn't find anything in README about a package which was I think your inspiration.
https://github.com/lukasz-galka/ngx-gallery
I think it's almost a copy of this project with an update to the new angular version.
I think it's worth to mention the original author and give some credits for him.

I know that the original package is probably abandoned but still most of the works have been done by him.

**Comment by kolkov** [comment]
Yes, it will be necessary to add this, as long as it is only in the original package in the issues section.

**Comment by obenjiro** [comment]
@kolkov I also want to add:

1) You actually violating MIT license by removing original author from LICENSE.md and not giving original author any credit.

MIT License have only one important rule "The MIT license requires that "the above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

You can write this in LICENSE.md

Copyright (c) 2017 Your Name
Copyright (c) 2015-2016 Previous Developer's Name
Copyright (c) 2014-2016 Other Project Developer's Name

Or you can have your own LICENCE.md with only your name but you should include original MIT license to every file that was forked (put it on top of file)

2) Attributing previous author is a nice thing to do :) I know that you would also wanted that your work to be credited and mentioned.

**Comment by kolkov** [comment]
@obenjiro thanks for the detailed comment. I will add this info in next update.
