### ISSUE TITLE
ngx-gallery v2 with Angular13 [Image display problem]

### ISSUE THREAD

**Issue by muratcanbatibay** [kolkov/ngx-gallery#89]
Hi,
I installed ngx-gallery v2 in my Angular13 project. When I run the project I don't get any errors but I can't display any images either.

### My Codes

  getPhotosByCityId(id: number) {
    this.cityService.getPhotosByCityId(id).subscribe(response => { this.photos = response })
    this.setGalery();
  }

  getImages() {
    const imgUrl = []
    for (let i = 0; i < this.city.photos.length; i++) {
      imgUrl.push(
        {
          small: this.city.photos[i].url,
          medium: this.city.photos[i].url,
          big: this.city.photos[i].url
        }
      )
    }
    return imgUrl;
  }

  setGalery() {
    this.galleryOptions = [
      {
        width: '100%',
        height: '400px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide
      },
      // max-width 800
      {
        breakpoint: 800,
        width: '100%',
        height: '600px',
        imagePercent: 80,
        thumbnailsPercent: 20,
        thumbnailsMargin: 20,
        thumbnailMargin: 20
      },
      // max-width 400
      {
        breakpoint: 400,
        preview: false
      }
    ];
    this.galleryImages = this.getImages();
  }
}
### Html
<ngx-gallery *ngIf="galleryImages" [options]="galleryOptions" [images]="galleryImages" class="ngx-gallery"></ngx-gallery>
    
Please can someone help me?

**Comment by Vikas4790** [comment]
Not sure, but is it related to issue #88. I am not able to load the lazy module itself which is registering(importing) the `ngx-gallery` module in Angular13 application with ngx-gallery v2.

**Comment by muratcanbatibay** [comment]
> Not sure, but can it be related to issue #88. I am not able to load the lazy module itself when registering (importing) the `NgxGalleryModule` in Angular13 application with ngx-gallery v2. 

But i can not see any error(s) on display..

**Comment by Vikas4790** [comment]
Is this a lazy module component that is using `ngx-gallery` component? I too do not see any error in the console ourput. It is just that the entire lazy module is not loading when I go to the url that loads the lazy module. 
Though, I was able to get the error message only when I tried to create a fresh angular13 app and import the `NgxGalleryModule`.

**Comment by muratcanbatibay** [comment]
> Is this a lazy module component that is using `ngx-gallery` component? I too do not see any error in the console ourput. It is just that the entire lazy module is not loading when I go to the url that loads the lazy module. 
> Though, I was able to get the error message only when I tried to create a fresh angular13 app and import the `NgxGalleryModule`. 


I don't use lazy module.
When i getting pictures without use ngx-gallery, i displaying on the screen. But while i use ngx-gallery, i can not display any pictures.

.. 
 When not using lazy module, can you displaying anything?

**Comment by muratcanbatibay** [comment]
**_This issue was resolved after the update .._**

_**Thanks for  the update.**_
