### ISSUE TITLE
Let carousel move on finger swipe for mobile view

### ISSUE THREAD

**Issue by windcloak** [kolkov/ngx-gallery#9]
I know pressing the left/right arrows will make the carousel move, but swiping it to left/right doesn't do anything. I would like to suggest that the carousel moves on finger swipe, like how Bootstrap's carousel does. (I already set imageSwipe: true and it's still not doing the swipe on mobile.)

**Comment by kolkov** [comment]
Hi! Do you have `HammerJS` installed and imported?

**Comment by windcloak** [comment]
I didn't have it imported correctly earlier. I forgot it used that for swipe! It's working now.
